### ISSUE TITLE
Youtube Docking mini player subtitle size

### ISSUE THREAD

**Issue by cmhrky** [alike03/Userscripts#2]
Hi,

If subtitle is enabled, its size does not decreased in the mini player. Is there a way to resize the subtitle for the mini player or can it be disabled in the mini player?

**Comment by alike03** [comment]
Since I never use subtitles this never occurred to me.
I did some testing. It looks fixable. YouTube is making things not easy.
Right now I don't have much time, but I will fix it as soon as I can.

**Comment by alike03** [comment]
With the new update in theater mode it should work properly now.

**Comment by cmhrky** [comment]
Thanks for the update, but it looks like this.

![image](https://user-images.githubusercontent.com/17867666/79160818-1a450300-7de3-11ea-9ffe-c0487876ce7e.png)

**Comment by alike03** [comment]
Thanks for the info. Looks like a chrome bug. Should be fixed now.

**Comment by cmhrky** [comment]
> "In Theater mode, video is now also in docked format scrollable with mouse clicks"

I guess it can't be used this way without turning on the theater mode. But it would be nice to be able to use it in this way without turning on the theatermode.

**Comment by alike03** [comment]
Unfortunately I couldn't find a native way to resize all the player elements in normal mode. And since they are all dynamic doing it by hand is quite a hassle. But I'm positive that there is one. I will add it as soon as I find it.
